site_name: Ployer
repo_url: https://github.com/StudSec/Ployer
site_url: https://StudSec.github.io/Ployer
site_description: CTF Challenge deployment tool for our format
site_author: StudSec
edit_uri: edit/main/docs/
repo_name: StudSec/Ployer
copyright: Maintained by <a href="https://StudSec.com">StudSec</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/ployer"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/StudSec/Ployer
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/Ployer

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
